id: I15421630
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W8601
  source: bdrc.io
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  ocr_info: {}
  op_import_options: {}
  op_import_version: 0.9.5
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-10-18T09:26:21.332407+00:00'
last_modified: '2022-10-18T09:26:21.332420+00:00'
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W8601
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8601
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་སྤྱི་དོན་ལེགས་བཤད་སྐལ་བཟང་མགུལ་རྒྱན།
  languages:
  - bo
  author: སེ་ར་རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9655696816573994
  ocr_word_median_confidence_index: 0.99941176
quality: null
bases:
  I1KG8869:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8869
      total_pages: 412
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8869.txt
    statistics:
      ocr_word_median_confidence_index: 0.99941176
      ocr_word_mean_confidence_index: 0.9655696816573994
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
